P5/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include("myapp.urls")),
    path('page1/',views.page1,name="page1"),
    path('page2/',views.page2,name='page2'),

]

myapp/urls.py
from django.urls import path
from myapp import views
app_name='myapp'

urlpatterns=[
    path('page3/',views.page3,name="page3"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render

# Create your views here.
def page1(request):
    
    return render(request,'sample1.html',context={'data':"Raju"})

def page2(request):
    d={'info':"DJANGO class"}
    return render(request,'sample2.html',context=d)
    
def page3(request):
    return render(request,'sample3.html')
    

templates/sample1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sample1</title>
    <link rel="stylesheet" href="{% static 'CSS/sam.css' %}">
</head>
<body>
    <h1>Hello {{data}}</h1>
    <a href="{% url 'page2' %}">move_to_sample2</a>
    <br/>
    <a href="{% url 'myapp:page3' %}">move_to_sample3</a>
    <img src="{% static 'images/img.png' %}" alt="mage not displayed">
    
</body>
</html>

templates/sample2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>sample2</title>
</head>
<body>
    <h1>Welcome to {{info}}</h1>
    <a href="{% url 'myapp:page3' %}">move_to_sample3</a>
    <br/>
    <a href="{% url 'page1' %}">move_to_sample1</a>
</body>
</html>

templates/sample3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>sample3</title>
</head>
<body>
    <h1>welcome to sample3</h1>
    <a href="{% url 'page1' %}">move_to_sample1</a><br/>
    <a href="{% url 'page2' %}">move_to_sample2</a>
    
</body>
</html>